### ISSUE TITLE
Consolidate Docker images

### ISSUE THREAD

**Issue by ArtemSokolov** [HMS-IDAC/UnMicst#3]
There is no longer any real need to build CPU and GPU containers in parallel. Per https://github.com/labsyspharm/mcmicro/issues/68, the Dockerfile should just build a GPU container (which can still be executed in a CPU-only environment).

Suggested changes:
1. Delete `hooks/build` from the repo
2. Simplify Dockerfile to use `FROM tensorflow/tensorflow:2.1.0-gpu-py3`

**Comment by clarenceyapp** [comment]
resolved in version 2.4.7
