### ISSUE TITLE
Can't get it to work 

### ISSUE THREAD

**Issue by josenimo** [HMS-IDAC/UnMicst#9]
Dear UnMicst developers,

I am trying to run MCMICRO for images taken by my collaborators. I have tried many different settings but unfortunately the pipeline runs into errors. By checking the _qc_ folder I was able to see that the UnMicst was not working appropriately, no pixels were visible (unless I pulled the histogram all the way, to see a repetitive pattern). As the tutorial mentions I tried to correct for the scalingFactor. However, I am not entirely sure the problems are due to that since I tried a variety of scalingFactors (0.1, 0.2, 0.25, 0.5, 0.75, 1.5, 2, 3, 4, 10) to no avail. No shapes could be seen in the qc files. My image has a resolution of 5.9557 pixels per micron, or about 0.1679 microns/pixel. Which is 0.25 of your training data resolution (0.65um/px). 

My command was the following: 
`nextflow run labsyspharm/mcmicro --in MCMICRO_13/ --start-at probability-maps --unmicst-opts '--scalingFactor 0.25' --s3seg-opts '--logSigma 10 100'`

File Download Link: https://filetransfer.mdc-berlin.de/?u=d3k4n9Jg&p=PcYnYZnK

Thank you so much for your amazing software, and your help!
Best,
Jose Nimo

**Comment by ArtemSokolov** [comment]
Hi @josenimo,

Thanks for your kind words about our tools.

I suspect the issue may be a small dynamic range in the input channel. UnMicst has `--mean` and `--std` parameters (The fourth item on this list: https://github.com/HMS-IDAC/UnMicst#parameter-list) that can be used to guide the tool towards where the signal is.

Take a look at https://forum.image.sc/t/imaging-mass-cytometry-analysis-from-mcd-file/56732/17 It has a small Python script that can be used to determine what the average intensity is in a given channel. You can then use that value as a starting point for UnMicst's `--mean` and play around with smaller/larger values to get the correct number of nuclei detected.

I am out today but can take a closer look tomorrow or Wednesday if you can't get it working by then. (Not sure if @clarenceyapp has time today.)

Cheers,
-Artem

**Comment by clarenceyapp** [comment]
@josenimo @ArtemSokolov I will have a look today but in general, yes, try using values of 0.0005 or 0.005 for both `--mean` and `--std`. These parameters help to account for images that are very far off from the training data.

Clarence

**Comment by ArtemSokolov** [comment]
Hi @josenimo,

Just wanted to check in and see if you had any luck with adding `--mean 0.0005 --std 0.0005` to the command-line options.

-Artem

**Comment by josenimo** [comment]
Hey @ArtemSokolov @clarenceyapp,

`--mean 0.0005 --std 0.0005` was successful in created proper probability maps. I am now playing around with scimap to get the visualization right. Thank you for checking on me. 

-Jose

**Comment by clarenceyapp** [comment]
Great! Glad it worked!
